html = "<!DOCTYPE html>"
html += "<html>"
html += "<head>"
html += "<title>ESP8266 WiFi Car</title>"
html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
html += "<style>body {background-color: Moccasin;} h1 {color: SaddleBrown;} h2 {color: Olive;}</style>"
html += "</head>"
html += "<body>"
html += "<div align=\"center\">"
html += "<h1>ESP8266 WiFi Car</h1>"
html += "<h2>Press \"stop\" after the server has been reset</h2>"
html += "<br>\n"
html += "<form method=\"GET\">"
html += "<input type=\"button\" value=\"Go forward\" onclick=\"window.location.href='/forward'\">"
html += "<br><br>\n"
html += "<input type=\"button\" value=\"Go backward\" onclick=\"window.location.href='/backward'\">"
html += "<br><br>\n"
html += "<input type=\"button\" value=\"Turn left\" onclick=\"window.location.href='/left'\">"
html += "<br><br>\n"
html += "<input type=\"button\" value=\"Turn right\" onclick=\"window.location.href='/right'\">"
html += "<br><br>\n"
html += "<input type=\"button\" value=\"Car stop\" onclick=\"window.location.href='/stop'\">"
html += "</form>\n"
html += "</div>\n"
html += "</body>\n"
html += "</html>\n"
print(html)